### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kimiko-i** [kimiko-i/protospace-31997#1]
[protospaceのURL](https://protospace-31997.herokuapp.com/)

**Comment by mutorisa** [comment]
ご提出ありがとうございます(^^)
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**

- [ ] 新規登録後、プロトタイプを保存しようとしたところでエラーがでてしまいました。エラーが出ないよう修正しましょう。

**※エラー発生により。総体的に挙動確認ができていいない為、次回ご提出時に改めて確認させていただきます。**

＜エラー画面＞
![Uploading スクリーンショット 2020-11-12 10.17.14.png…]()


修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7
※新しいissueを作っていただく必要はありません

**Comment by kimiko-i** [comment]
いつもありがとうございます。
修正いたしました。よろしくお願いいたします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、前回修正を依頼した箇所は確認ができました🎉

今回新たに修正をお願いしたい箇所がございます！
[修正箇所]

**○ログアウトした状態でも、プロトタイプ一覧、詳細ページを閲覧できるようにしましょう**

**○他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、
トップページにリダイレクトされるようにしましょう**
→現状、他のユーザーが投稿したプロトタイプの編集ページに遷移、編集できてしまいます

修正でき次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kimiko-i** [comment]
お世話になっております。いつもありがとうございます。
- ログアウト後のリダイレクト先の変更
- editアクションの制限
上記２箇所を修正いたしました。
よろしくお願いいたします。
[URL](https://protospace-31997.herokuapp.com/)

**Comment by mutorisa** [comment]
池田さん、再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
